### ISSUE TITLE
Current version on PyPI does not contain recent changes

### ISSUE THREAD

**Issue by martinschwinzerl** [rdemaria/pysixtrack#12]
Most notably, the BeamMonitor introduced in commit 3c0dcebc is not present in the version installable via pip, causing pysixtracklib to fail on a vanilla installation.

**Comment by rdemaria** [comment]
I can fix it only on Monday...

**Comment by rdemaria** [comment]
Perhaps I fixed it..

**Comment by martinschwinzerl** [comment]
Thank you & no pressure! I created the issue just to not forget again about it :-)

**Comment by martinschwinzerl** [comment]
Seems to be fixed, thank you for the swift response!
Cheers,
Martni
